# Python Project 
Python is a versatile, high-level programming language known for its readability and ease of use. It is widely used in various fields, including web development, data analysis, artificial intelligence, scientific computing, and more.
It was created by Guido van Rossum, and released in 1991.


## 1.	Python Operators:Operators perform operations on values and variables


In [1]:
#Arithmetic Operators: Used for mathematical operations.

a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))

sum_result = a + b
product_result = a * b
quotient = a / b
remainder = a % b
Subtraction = a - b
Exponentiation = a ** b
Floor_division = a // b

print("Sum:", sum_result)
print("Product:", product_result)
print("Quotient:", quotient)
print("Remainder:", remainder)
print("Subtraction:", Subtraction)
print("Exponentiation:", Exponentiation)
print("Floor Division:", Floor_division) #he result is rounded down to the nearest integer

Enter 1st number:  12
Enter 2nd number:  25


Sum: 37
Product: 300
Quotient: 0.48
Remainder: 12
Subtraction: -13
Exponentiation: 953962166440690129601298432
Floor Division: 0


In [2]:
#Comparison Operators: Used to compare values.
x = int(input("Enter 1st number: "))
y = int(input("Enter 2nd number: "))

print(x == y)
print(x > y)
print(x <= y)
print(x != y)
print(x < y)
print(x >= y)

Enter 1st number:  23
Enter 2nd number:  24


False
False
True
True
True
False


In [3]:
#Logical Operators: Combine multiple conditions.
x = int(input("Enter 1st number: "))
y = int(input("Enter 2nd number: "))

print(x > 5 and y < 10)
print(x < 5 or y == 5)
print(not (x == 10))

Enter 1st number:  13
Enter 2nd number:  67


False
False
True


In [4]:
#Assignment Operators: Assign values to variables, optionally performing an operation at the same time.

a,x,y,z = 10,20,30,40

a += 5
print(a)

x *= 2
print(x)

y -= 3
print(y)

z /= 4
print(z)

15
40
27
10.0


In [5]:
#bitwise Operator
a = 12   # binary: 1100
b = 7    # binary: 0111
print(a & b)  #AND (&): Performs a bitwise AND operation. Each bit of the result is 1 if the corresponding bits of both operands are 1, otherwise 0.
print(a | b)  #OR (|): Performs a bitwise OR operation. Each bit of the result is 1 if at least one of the corresponding bits of either operand is 1.
print(a ^ b)  #XOR (^): Performs a bitwise XOR operation. Each bit of the result is 1 if the corresponding bits of the operands are different, otherwise 0.
print(~a)     #Performs a bitwise NOT operation (one's complement).
print(a << 2) #Left Shift (<<): Shifts the bits of the operand to the left by the number of positions specified.
print(a >> 2) #Right Shift (>>): Shifts the bits of the operand to the right by the number of positions specified.

4
15
11
-13
48
3


In [7]:
#Operator Precedence
#The order in which operators are evaluated in an expression.
# Precedence Table (from highest to lowest):
# ** (Exponentiation)
# *, /, //, % (Multiplication, division, modulus)
# +, - (Addition, subtraction)
# ==, !=, >, <, >=, <= (Comparison)
# not (Logical NOT)
# and (Logical AND)
# or (Logical OR)

result = (5 + 2) * 3 ** 2 / 2
print(result)

31.5


## 2. Lists
- Definition: Lists are ordered, mutable (can be changed), and allow duplicate elements.
- Use Case: Managing a list of items such as shopping cart products, task lists, or employee names.

In [8]:
# Creating a list of student names
students = ["John", "Alice", "Bob"]
print(students)

['John', 'Alice', 'Bob']


In [9]:
#positive index
print(students[0])

#Negative indexing
print(students[-1])

John
Bob


In [10]:
# Changing the first element

students[0] = "Tom"
print(students)

['Tom', 'Alice', 'Bob']


In [11]:
# Inserting a student at index 1
students.insert(1, "Mike")
print(students)

['Tom', 'Mike', 'Alice', 'Bob']


In [12]:
# Extending the list with another list
students.extend(["Emma", "James"])
print(students)

['Tom', 'Mike', 'Alice', 'Bob', 'Emma', 'James']


In [13]:
# Removing a specific student
students.remove("Mike")
print(students)

# Removing the last element
students.pop()
print(students)

# Removing an element by index
students.pop(2)
print(students)

# Clearing the entire list
students.clear()
print(students)

['Tom', 'Alice', 'Bob', 'Emma', 'James']
['Tom', 'Alice', 'Bob', 'Emma']
['Tom', 'Alice', 'Emma']
[]


In [14]:
#Slicing Lists
numbers = [10, 20, 30, 40, 50, 60, 70]

# Slicing from index 1 to 4
print(numbers[1:4])

# Slicing from the start to index 3
print(numbers[:3])

# Slicing from index 2 to the end
print(numbers[2:])

# Slicing with a step (every second element)
print(numbers[::2])

# Slicing with a negative step (reversing the list)
print(numbers[::-1])

[20, 30, 40]
[10, 20, 30]
[30, 40, 50, 60, 70]
[10, 30, 50, 70]
[70, 60, 50, 40, 30, 20, 10]


In [16]:
#to do list 
# List of tasks
tasks = ["Complete assignment", "Attend meeting", "Pay bills"]

# Adding a new task
tasks.append("Go grocery shopping")
print(tasks)

# Marking a task as done (removing from the list)
tasks.remove("Attend meeting")
print(tasks)

['Complete assignment', 'Attend meeting', 'Pay bills', 'Go grocery shopping']
['Complete assignment', 'Pay bills', 'Go grocery shopping']


In [20]:
#sort() method (which sorts in place) or the sorted() function (which returns a new sorted list).
numbers = [5, 2, 9, 1, 5, 6]

# Sort in ascending order
numbers.sort()
print(numbers)

# Sort in descending order
numbers.sort(reverse=True)
print(numbers)

#sorted() Function
a = ("b", "g", "a", "d", "f", "c", "h", "e")
x = sorted(a)
print(x)

[1, 2, 5, 5, 6, 9]
[9, 6, 5, 5, 2, 1]
['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']


In [21]:
# Shopping cart with products
shopping_cart = ["apple", "banana", "milk", "bread"]
print(shopping_cart)

# Check if an item is in the list
print("milk" in shopping_cart)

# Sorting the list alphabetically
shopping_cart.sort()
print(shopping_cart)

# Reversing the list
shopping_cart.reverse()
print(shopping_cart)

# Counting occurrences of an element
print(shopping_cart.count("milk"))

['apple', 'banana', 'milk', 'bread']
True
['apple', 'banana', 'bread', 'milk']
['milk', 'bread', 'banana', 'apple']
1


## 3. Tuples
- Definition: Tuples are ordered, immutable (cannot be changed after creation), and allow duplicate elements.
- Use Case: Storing fixed data like coordinates, days of the week, or configuration settings.

In [22]:
# Creating a tuple
student_info = ("John", 22, "Computer Science")
print(student_info)

('John', 22, 'Computer Science')


In [24]:
#Positive indexing

print(student_info[0])
print(student_info[1])

#Negative indexing
print(student_info[-1])

John
22
Computer Science


In [25]:
# Tuple with duplicates
fruits = ("apple", "banana", "apple", "cherry")
print(fruits)

('apple', 'banana', 'apple', 'cherry')


In [26]:
# A tuple with multiple data types
student_data = ("Bob", 25, True, 3.9)

# Unpacking
name, age, is_enrolled, GPA = student_data
print(f"Name: {name}, Age: {age}, Enrolled: {is_enrolled}, GPA: {GPA}")

Name: Bob, Age: 25, Enrolled: True, GPA: 3.9


In [27]:
#Storing Days of the Week
days_of_week = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
# Accessing a specific day
print(days_of_week[0])
print(days_of_week[5])
print(days_of_week[-2])

Monday
Saturday
Saturday


In [28]:
# A tuple of tuples
class_schedule = (("Math", "9 AM"), ("Physics", "11 AM"), ("Chemistry", "1 PM"))

# Accessing nested tuples
print(class_schedule[0])
print(class_schedule[1][1])

('Math', '9 AM')
11 AM


In [29]:
#Update tuple
x = ("apple", "banana", "cherry")
y = list(x)  #Tuples are unchangeable so convert the tuple into a list, change the list, and convert the list back into a tuple.
y[1] = "kiwi"
x = tuple(y)

print(x)

('apple', 'kiwi', 'cherry')


In [30]:
#Tuple Methods
numbers = (1, 2, 3, 4, 1, 2, 1)
print(numbers.count(1))
print(numbers.index(3))

3
2


In [31]:
#Join Two Tuples
tuple1 = ("a", "b" , "c")
tuple2 = (1, 2, 3)

tuple3 = tuple1 + tuple2 #To join two or more tuples you can use the + operator:
print(tuple3)


('a', 'b', 'c', 1, 2, 3)


In [32]:
#Multiply Tuples
fruits = ("apple", "banana", "cherry")
mytuple = fruits * 4 # multiply the content of a tuple a given number of times, you can use the * operator

print(mytuple)

('apple', 'banana', 'cherry', 'apple', 'banana', 'cherry', 'apple', 'banana', 'cherry', 'apple', 'banana', 'cherry')


In [33]:
#Unpacking a Tuple
# in Python, we are also allowed to extract the values back into variables. This is called "unpacking":
fruits = ("apple", "banana", "cherry")

(green, yellow, red) = fruits

print(green)
print(yellow)
print(red)

apple
banana
cherry


In [34]:
#Using Asterisk*
fruits = ("apple", "banana", "cherry", "strawberry", "raspberry")

#variables is less than the number of values, you can add an * to the variable name and the values will be assigned to the variable as a list
(green, yellow, *red) = fruits

print(green)
print(yellow)
print(red)

apple
banana
['cherry', 'strawberry', 'raspberry']


In [35]:
fruits = ("apple", "mango", "papaya", "pineapple", "cherry")

(green, *tropic, red) = fruits

print(green)
print(tropic)
print(red)

apple
['mango', 'papaya', 'pineapple']
cherry


## 4.Sets
- Definition: Sets are unordered, mutable (but elements themselves must be immutable), and do not allow duplicates. bold text
- Use Case: Managing a collection of unique items like email addresses, tags, or product categories.

In [36]:
thisset = {"apple", "banana", "cherry"}
print(thisset)

{'apple', 'banana', 'cherry'}


In [37]:
#Duplicates Not Allowed
thisset = {"apple", "banana", "cherry", "apple"}

print(thisset)

{'apple', 'banana', 'cherry'}


In [38]:
#Length of a Set
print(len(thisset))

3


In [39]:
#Access Set Items
thisset = {"apple", "banana", "cherry"}

print("banana" in thisset)

True


In [40]:
#Loop Items
thisset = {"apple", "banana", "cherry"}

for x in thisset:
  print(x)


apple
banana
cherry


In [41]:
#Add Set Items
thisset = {"apple", "banana", "cherry"}

thisset.add("orange")

print(thisset)

{'apple', 'banana', 'cherry', 'orange'}


In [42]:
#To add items from another set into the current set
thisset = {"apple", "banana", "cherry"}
tropical = {"pineapple", "mango", "papaya"}

thisset.update(tropical)

print(thisset)

{'pineapple', 'banana', 'mango', 'papaya', 'apple', 'cherry'}


In [43]:
#Add Any Iterable object (tuples, lists, dictionaries etc.).
thisset = {"apple", "banana", "cherry"}
mylist = ["kiwi", "orange"]

thisset.update(mylist)

print(thisset)

{'banana', 'apple', 'cherry', 'kiwi', 'orange'}


In [44]:
thisset = {"apple", "banana", "cherry"}

thisset.remove("banana")

print(thisset)

{'apple', 'cherry'}


In [45]:
#Join Sets
set1 = {"a", "b", "c"}
set2 = {1, 2, 3}

set3 = set1.union(set2)
print(set3)

{1, 2, 3, 'c', 'a', 'b'}


In [46]:
set1 = {"a", "b", "c"}
set2 = {1, 2, 3}

set3 = set1 | set2
print(set3)

{1, 2, 3, 'c', 'a', 'b'}


In [47]:
set1 = {"a", "b", "c"}
set2 = {1, 2, 3}
set3 = {"John", "Elena"}
set4 = {"apple", "bananas", "cherry"}

myset = set1.union(set2, set3, set4)
print(myset)

{'Elena', 1, 2, 3, 'apple', 'cherry', 'b', 'bananas', 'John', 'c', 'a'}


In [48]:
set1 = {"a", "b", "c"}
set2 = {1, 2, 3}
set3 = {"John", "Elena"}
set4 = {"apple", "bananas", "cherry"}

myset = set1 | set2 | set3 |set4
print(myset)

{'Elena', 1, 2, 3, 'apple', 'cherry', 'b', 'bananas', 'John', 'c', 'a'}


In [49]:
team_a_skills = {"Python", "SQL", "Data Engineering"}
team_b_skills = {"SQL", "Cloud", "Data Science"}

# Union of both sets
all_skills = team_a_skills | team_b_skills
print(all_skills)

#Returns a set, that is the intersection of two other sets
common_skills = team_a_skills & team_b_skills
print(common_skills)

#Returns a set containing the difference between two or more sets
a_not_in_b = team_a_skills - team_b_skills
print(a_not_in_b)

{'Cloud', 'Data Science', 'Data Engineering', 'Python', 'SQL'}
{'SQL'}
{'Python', 'Data Engineering'}


In [50]:
# Unique email addresses
email_addresses = {"john@example.com", "jane@example.com", "john@example.com"}

# Adding an element to the set
email_addresses.add("mark@example.com")

# Removing an element from the set
email_addresses.remove("john@example.com")

# Set operations (union, intersection)
another_set = {"susan@example.com", "jane@example.com"}

# Union: Combine two sets
all_emails = email_addresses.union(another_set)
print(all_emails)

# Intersection: Find common elements
common_emails = email_addresses.intersection(another_set)
print(common_emails)

# Checking the length of the set
print(len(email_addresses))

{'jane@example.com', 'mark@example.com', 'susan@example.com'}
{'jane@example.com'}
2


In [51]:
#warehouse
# Current stock in warehouse
stock = {"laptop", "tablet", "smartphone"}

# New shipment arrives
stock.add("desktop")

# Item sold
stock.discard("tablet")

print(stock)

{'smartphone', 'laptop', 'desktop'}


## 5.Dictionaries
- Definition: Dictionaries are unordered collections of key-value pairs, where each key must be unique.
- Use Case: Storing related data like user profiles, product details, or settings.

In [52]:
# Creating a simple dictionary
student = {
    "name": "John",
    "age": 22,
    "major": "Computer Science"
}
print(student)
print(student["name"])
print(student["age"])

{'name': 'John', 'age': 22, 'major': 'Computer Science'}
John
22


In [53]:
# Adding a new key-value pair for GPA
student["GPA"] = 3.8
print(student)

# Removing an element using del
del student["GPA"]
print(student)

# Removing an element using pop
age = student.pop("age")
print(age)
print(student)

{'name': 'John', 'age': 22, 'major': 'Computer Science', 'GPA': 3.8}
{'name': 'John', 'age': 22, 'major': 'Computer Science'}
22
{'name': 'John', 'major': 'Computer Science'}


In [54]:
# Iterating through keys
for key in student:
    print(key)

# Iterating through values
for value in student.values():
    print(value)

# Iterating through key-value pairs
for key, value in student.items():
    print(f"{key}: {value}")

name
major
John
Computer Science
name: John
major: Computer Science


In [55]:
#Counting Word Frequency
sentence = "python is great and python is popular"
words = sentence.split()

word_count = {}

for word in words:
    if word in word_count:
        word_count[word] += 1
    else:
        word_count[word] = 1

print(word_count)

{'python': 2, 'is': 2, 'great': 1, 'and': 1, 'popular': 1}


In [56]:
#User Profile Management:

user_profile = {
    "username": "johndoe",
    "email": "john@example.com",
    "age": 30,
    "is_active": True
}

# Access user information
print(user_profile["email"])

john@example.com


In [58]:
# Update user email
user_profile["email"] = "johndoe_new@example.com"
print(user_profile["email"])

johndoe_new@example.com


In [59]:
#Copy a Dictionary
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
mydict = thisdict.copy()
print(mydict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [60]:
#Make a copy of a dictionary with the dict() function:
thisdict = {
  "brand": "Ford",
  "model": "Mustang",
  "year": 1964
}
mydict = dict(thisdict)
print(mydict)

{'brand': 'Ford', 'model': 'Mustang', 'year': 1964}


In [61]:
#Nested Dictionaries
myfamily = {
  "child1" : {
    "name" : "Emil",
    "year" : 2004
  },
  "child2" : {
    "name" : "Tobias",
    "year" : 2007
  },
  "child3" : {
    "name" : "Linus",
    "year" : 2011
  }
}

print(myfamily["child2"]["name"])


Tobias


# 6.If ... Else

In [66]:
a = 33
b = 33
if b > a:
  print("b is greater than a")
elif a == b:   #if the previous conditions were not true, then try this condition
  print("a and b are equal")

a and b are equal


In [69]:
#Conditional Logic in Python: if, else, and elif

temperature = int(input("Enter temperature: "))

if temperature > 35:
    print("It's very hot outside!")
elif temperature > 25:
    print("It's a pleasant day.")
else:
    print("It's a bit cold.")

Enter temperature:  20


It's a bit cold.


In [63]:
#Complex Conditional Expressions:

age = input("Enter your age: ")
age = int(age)
has_license = True

if age >= 18 and has_license:
    print("You are allowed to drive.")
else:
    print("You are not allowed to drive.")

Enter your age:  65


You are allowed to drive.


In [64]:
#Nested if Statements:
score = int(input("Enter your age: "))

if score >= 50:
    print("You passed the exam.")
    if score >= 80:
        print("You passed with distinction!")
else:
    print("You failed the exam.")

Enter your age:  65


You passed the exam.


In [65]:
#loan eligibility check

age = int(input("Enter your age: "))
income = int(input("Enter your income: "))
credit_score = int(input("Enter your credit score: "))

if age >= 21:
    if income >= 50000:
        if credit_score >= 650:
            print("You are eligible for a loan.")
        else:
            print("Your credit score is too low for loan approval.")
    else:
        print("Your income is insufficient for loan approval.")
else:
    print("You are not old enough to apply for a loan.")

Enter your age:  34
Enter your income:  200000
Enter your credit score:  700


You are eligible for a loan.


# 7. While Loop: A while loop repeats a block of code as long as a given condition is true. It checks the condition before each iteration.

In [70]:
#Checking Balance Until Minimum Limit
# Check the bank balance. If you want to keep withdrawing money until you hit the minimum balance limit.

balance = 10000
min_balance = 1000
while balance >= min_balance:
    print(f"Current Balance: {balance}")
    withdraw = 1000  # Let's assume a fixed withdrawal
    balance -= withdraw  # Reducing balance

print("Your account is at the minimum balance limit.")

Current Balance: 10000
Current Balance: 9000
Current Balance: 8000
Current Balance: 7000
Current Balance: 6000
Current Balance: 5000
Current Balance: 4000
Current Balance: 3000
Current Balance: 2000
Current Balance: 1000
Your account is at the minimum balance limit.


In [71]:
#Allow a user 3 attempts to log in before locking their account.
#The getpass module provides a secure way to handle the password prompts where programs interact with the users via the terminal.Basically getpass.getpass() is used to hide the password input.

import getpass

correct_password = "correct_password123"
attempts = 3

while attempts > 0:
    password = getpass.getpass("Enter your password: ")

    if password == correct_password:
        print("Login Successful!")
        break
    else:
        attempts -= 1
        print(f"Incorrect password! You have {attempts} attempts left.")

if attempts == 0:
    print("Your account is locked.")

Enter your password:  ········


Incorrect password! You have 2 attempts left.


Enter your password:  ········


Incorrect password! You have 1 attempts left.


Enter your password:  ········


Login Successful!


In [72]:
# there might be a scenario where passengers board until the aircraft reaches full capacity.

aircraft_capacity = 180  # Total number of seats
current_passengers = 0  # Starting with no passengers onboard

while current_passengers < aircraft_capacity:
    print(f"Passenger {current_passengers + 10} boarding...")
    current_passengers += 10  # Increment passenger count

print("Boarding complete. Aircraft is at full capacity.")


Passenger 10 boarding...
Passenger 20 boarding...
Passenger 30 boarding...
Passenger 40 boarding...
Passenger 50 boarding...
Passenger 60 boarding...
Passenger 70 boarding...
Passenger 80 boarding...
Passenger 90 boarding...
Passenger 100 boarding...
Passenger 110 boarding...
Passenger 120 boarding...
Passenger 130 boarding...
Passenger 140 boarding...
Passenger 150 boarding...
Passenger 160 boarding...
Passenger 170 boarding...
Passenger 180 boarding...
Boarding complete. Aircraft is at full capacity.


In [73]:
#The fuel level is monitored during a flight, and the system needs to keep checking until the fuel level drops below a safety threshold.
fuel_level = 10000  # Initial fuel in liters
critical_fuel_level = 1500  # Critical fuel level in liters

while fuel_level > critical_fuel_level:
    print(f"Fuel level is {fuel_level} liters.")
    # Simulate fuel consumption
    fuel_consumed = 500  # Fuel consumption per iteration
    fuel_level -= fuel_consumed  # Decrease fuel level

print("Warning! Fuel level has dropped below the critical level.")

Fuel level is 10000 liters.
Fuel level is 9500 liters.
Fuel level is 9000 liters.
Fuel level is 8500 liters.
Fuel level is 8000 liters.
Fuel level is 7500 liters.
Fuel level is 7000 liters.
Fuel level is 6500 liters.
Fuel level is 6000 liters.
Fuel level is 5500 liters.
Fuel level is 5000 liters.
Fuel level is 4500 liters.
Fuel level is 4000 liters.
Fuel level is 3500 liters.
Fuel level is 3000 liters.
Fuel level is 2500 liters.
Fuel level is 2000 liters.
Warning! Fuel level has dropped below the critical level.


## While Loop with continue and break
- continue: Skips to the next iteration by rechecking the condition without executing the rest of the loop body.
- break: Exits the loop and stops further execution, regardless of the condition.

In [74]:
#Scenario: Passenger Boarding Process with Security Check
#During the boarding process, passengers are checked before entering the aircraft. If a passenger fails a security check, they are not allowed to board (loop skips them using continue). If a major issue occurs (e.g., a security alert), the entire boarding process is stopped (break).

total_passengers = 10
current_passenger = 1

while current_passenger <= total_passengers:
    # Simulating security check
    if current_passenger == 5:  # Passenger 5 has failed the security check
        print(f"Passenger {current_passenger} failed security check. Skipping...")
        current_passenger += 1
        continue  # Skip this passenger and continue to the next

    if current_passenger == 8:  # A major security alert for passenger 8
        print(f"Security Alert! Passenger {current_passenger} poses a risk. Boarding halted.")
        break  # Stop the boarding process immediately

    print(f"Passenger {current_passenger} successfully boarded.")
    current_passenger += 1

Passenger 1 successfully boarded.
Passenger 2 successfully boarded.
Passenger 3 successfully boarded.
Passenger 4 successfully boarded.
Passenger 5 failed security check. Skipping...
Passenger 6 successfully boarded.
Passenger 7 successfully boarded.
Security Alert! Passenger 8 poses a risk. Boarding halted.


# 8.For Loop: A for loop is used to iterate over a sequence (such as a list, tuple, or string) and executes the block of code for each item in that sequence.

In [75]:
passengers = ["John", "Sarah", "Michael", "Alice", "David"]

for passenger in passengers:
    print(f"Boarding passenger: {passenger}")

Boarding passenger: John
Boarding passenger: Sarah
Boarding passenger: Michael
Boarding passenger: Alice
Boarding passenger: David


In [76]:
#Example 1: Warehouse Management Scenario - Processing Orders in a List
#Suppose a list of customer orders in a warehouse, and you need to process each order one by one.

orders = ["Order 1", "Order 2", "Order 3"]

for order in orders:
    print(f"Processing {order}")

Processing Order 1
Processing Order 2
Processing Order 3


In [77]:
#Analyzing Sensor Data
#You have temperature data collected every hour and want to alert if any temperature exceeds 100°F.
temperatures = [90, 102, 97, 85, 110, 95]

for temp in temperatures:
    if temp > 100:
        print(f"Alert! High temperature recorded: {temp}°F")

Alert! High temperature recorded: 102°F
Alert! High temperature recorded: 110°F


In [78]:
#Iterating through a list of maintenance tasks and checking them off as completed.
maintenance_checklist = [
    "Check engine oil levels",
    "Inspect landing gear",
    "Check avionics systems",
    "Inspect hydraulic systems",
    "Check fuel systems",
    "Test emergency lighting"
]

for task in maintenance_checklist:
    print(f"Completing task: {task}")

print("All maintenance tasks completed.")

Completing task: Check engine oil levels
Completing task: Inspect landing gear
Completing task: Check avionics systems
Completing task: Inspect hydraulic systems
Completing task: Check fuel systems
Completing task: Test emergency lighting
All maintenance tasks completed.


In [79]:
#Managing Aircraft Seating by Rows and Columns
#an aircraft with multiple rows of seats, and you want to assign passengers to their seats row by row.
#the chr() function returns the character that corresponds to the Unicode code point
#The expression chr(64 + seat) is adding the seat number to 64 in order to convert numbers like 1, 2, 3 into letters:

# chr(64 + 1) = chr(65) = 'A'
# chr(64 + 2) = chr(66) = 'B'
# chr(64 + 3) = chr(67) = 'C'

rows = 5
seats_per_row = 4

for row in range(1, rows + 1):
    for seat in range(1, seats_per_row + 1):
        print(f"Assigning seat {row}{chr(64 + seat)} to passenger")

Assigning seat 1A to passenger
Assigning seat 1B to passenger
Assigning seat 1C to passenger
Assigning seat 1D to passenger
Assigning seat 2A to passenger
Assigning seat 2B to passenger
Assigning seat 2C to passenger
Assigning seat 2D to passenger
Assigning seat 3A to passenger
Assigning seat 3B to passenger
Assigning seat 3C to passenger
Assigning seat 3D to passenger
Assigning seat 4A to passenger
Assigning seat 4B to passenger
Assigning seat 4C to passenger
Assigning seat 4D to passenger
Assigning seat 5A to passenger
Assigning seat 5B to passenger
Assigning seat 5C to passenger
Assigning seat 5D to passenger


In [80]:
#The break statement is triggered if there’s an engine failure, halting the entire checklist.
#The continue statement is triggered for a seatbelt issue, which allows the loop to skip to the next task after noting the minor issue.

safety_checklist = [
    "Check engine oil levels",
    "Inspect landing gear",
    "Check avionics systems",
    "Inspect hydraulic systems",
    "Check fuel systems",
    "Test emergency lighting",
    "Check landing gear",
    "Check fuel levels",
    "Check engine status",
    "Inspect seatbelts",
    "Test emergency exits"
]

for task in safety_checklist:
    if task == "Check engine status":
        print("Critical issue: Engine failure detected!")
        break  # Stop all checks if there's an engine issue
    elif task == "Inspect seatbelts":
        print("Minor issue: Seatbelt not adjusted properly. Fixing it.")
        continue  # Skip to the next task after fixing the seatbelt

    print(f"Performing task: {task}")

Performing task: Check engine oil levels
Performing task: Inspect landing gear
Performing task: Check avionics systems
Performing task: Inspect hydraulic systems
Performing task: Check fuel systems
Performing task: Test emergency lighting
Performing task: Check landing gear
Performing task: Check fuel levels
Critical issue: Engine failure detected!


# 9.Python Function

- Functions are a fundamental concept in Python that allow you to encapsulate code into reusable blocks.
- to create your own functions using the def keyword.

In [81]:
# Function with no parameters and no return value
def greet():
    print("Hello, world!")

# Function with one parameter and a return value
def square(num):
    return num ** 2

# Function with multiple parameters and return type
def sum_numbers(a, b, c):
    return a + b + c

greet()
print(square(4))
print(sum_numbers(1, 2, 3))

Hello, world!
16
6


In [82]:
#local (within the function) or global (accessible everywhere). Local variables are only available within the function they are defined in.

x = 10  # Global variable

def change_value():
    x = 5  # Local variable (does not affect global x)
    print("Inside function:", x)
change_value()
print("Outside function:", x)

Inside function: 5
Outside function: 10


In [83]:
#Functions with Default Argument Values
#If no argument is passed for a parameter, the default value is used.
def greet(name="Guest"):
    print(f"Hello, {name}!")

greet("Alice")
greet()

Hello, Alice!
Hello, Guest!


In [84]:
#Recursive functions call themselves within their body. 
#They are useful for tasks like traversing hierarchical data structures or solving problems like factorials or Fibonacci numbers.
def factorial(n):
    if n == 1:
        return 1
    else:
        return n * factorial(n - 1)

print(factorial(5))

120


In [85]:
#Using Docstrings to Document Functions
def my_function():
    '''Demonstrates triple double quotes
    docstrings and does nothing really.'''

    return None

print("Using __doc__:")
print(my_function.__doc__)

print("Using help:")
help(my_function)

Using __doc__:
Demonstrates triple double quotes
    docstrings and does nothing really.
Using help:
Help on function my_function in module __main__:

my_function()
    Demonstrates triple double quotes
    docstrings and does nothing really.



In [86]:
#Banking System:
#In a banking system, different functions can handle operations like deposits, withdrawals, and balance checks. 
#Local variables inside these functions do not affect global variables like the total account balance.

account_balance = 10000  # Global balance

def deposit(amount):
    global account_balance
    account_balance += amount
    print(f"${amount} deposited. New balance: ${account_balance}")

def withdraw(amount):
    global account_balance
    if amount > account_balance:
        print("Insufficient funds.")
    else:
        account_balance -= amount
        print(f"${amount} withdrawn. New balance: ${account_balance}")

def check_balance():
    print(f"Current balance: ${account_balance}")

In [87]:
# Banking operations
deposit(500)
check_balance()
withdraw(1500)
check_balance()

$500 deposited. New balance: $10500
Current balance: $10500
$1500 withdrawn. New balance: $9000
Current balance: $9000


In [88]:
#Email Automation
def send_email(to="customer@example.com", subject="No Subject", body=""):
    print(f"Sending email to {to}")
    print(f"Subject: {subject}")
    print(f"Body: {body}")

# Sending emails
send_email("alice@example.com", "Welcome", "Hello Alice, welcome to our service!")

Sending email to alice@example.com
Subject: Welcome
Body: Hello Alice, welcome to our service!


# 10.Lambda Functions : Lambda functions are small, anonymous functions defined with the lambda keyword. 

In [89]:
#Basic Lambda Function
add = lambda a, b: a + b
print(add(3, 5))

square = lambda x: x ** 2
print(square(4))

#Lambda with Multiple Arguments
maximum = lambda x, y: x if x > y else y
print(maximum(10, 15))

8
16
15


In [97]:
# Using Lambda Functions with Built-In Functions

nums = [1, 2, 3, 4]
squared_nums = list(map(lambda x: x ** 2, nums))
print(squared_nums)

[1, 4, 9, 16]


In [98]:
nums = [1, 2, 3, 4, 5, 6]
even_nums = list(filter(lambda x: x % 2 == 0, nums))
print(even_nums)

[2, 4, 6]


### Comparing Lambda Functions with Regular Functions

In [103]:
#Single-line, anonymous functions with no return statement.
add = lambda x, y: x + y
print(add(5, 7))

12


In [104]:
# Defined using the def keyword. They can have multiple lines, explicit return statements, and documentation.
def add(x, y):
    return x + y

print(add(5, 7))

12


# 11.Python String Methods:String methods are used for various operations on string data.

In [105]:
#String Concatenation

first_name = "John"
last_name = "Doe"
full_name = first_name + " " + last_name
print(full_name)

John Doe


In [106]:
#String Slicing
#Slicing allows you to extract a part of a string. It uses the syntax string[start:end:step]

string = "Hello, World!"
print(string[0:5]) #extracts the first 5 characters.
print(string[7:])  #extracts from index 7 to the end.
print(string[::-1]) #reverses the string.

Hello
World!
!dlroW ,olleH


In [107]:
#Finding Substrings
# find(substring): Returns the index of the first occurrence of the substring. Returns -1 if not found.
# in: Checks if a substring exists and returns a boolean.

sentence = "The quick brown fox"
print(sentence.find("quick"))

print("fox" in sentence)
print(sentence.count("o"))
print(sentence.startswith("The"))
print(sentence.endswith("fox"))
print(sentence.find("dog")) #returns -1 if the substring is not found.

4
True
2
True
True
-1


In [108]:
#Changing String Case

text = "Hello! How are you?"
print(text.upper()) #Converts all characters to uppercase.
print(text.lower()) #Converts all characters to lowercase.
print(text.title()) #Converts the first letter of each word to uppercase (title case).
print(text.capitalize()) # Converts only the first letter of the string to uppercase.

HELLO! HOW ARE YOU?
hello! how are you?
Hello! How Are You?
Hello! how are you?


In [109]:
#Removing Whitespace

text = "  Hello, World!  "

print(text.strip()) #Removes leading and trailing whitespace.
print(text.lstrip()) #Removes leading whitespace.
print(text.rstrip()) #Removes trailing whitespace.

Hello, World!
Hello, World!  
  Hello, World!


In [112]:
#Splitting and Joining Strings

#split(separator): Splits a string into a list based on a specified separator.
sentence = "The quick brown fox jumps over the lazy dog"
words = sentence.split()  # Default is splitting by space
print(words)

data = "name:John,age:30,city:New York"
entries = data.split(",")  # Split by comma
print(entries)

['The', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
['name:John', 'age:30', 'city:New York']


In [111]:
#join(iterable): Joins elements of an iterable (like a list) into a string, using a specified separator.
joined_sentence = " ".join(words)
print(joined_sentence)

The quick brown fox jumps over the lazy dog


In [113]:
#Replacing Substrings
sentence = "The cat sat on the mat."
new_sentence = sentence.replace("cat", "dog")
print(new_sentence)

The dog sat on the mat.


In [114]:
#String Length and Character Count

message = "banana"
print(len(message)) #Returns the number of characters in a string.
print(message.count('a')) # Counts how many times a substring appears in a string.

6
3


In [115]:
#Checking String Properties

text = "Python3"
print(text.startswith("Py")) #Checks if the string starts with a specified substring.
print(text.endswith("3")) #Checks if the string ends with a specified substring.
print(text.isalpha()) #Checks if all characters are alphabetic.
print(text.isdigit()) #Checks if all characters are numeric.

True
True
False
False


In [116]:
# User input
raw_input = input("Enter your email id:")

# Strip whitespace and convert to lowercase
cleaned_input = raw_input.strip().lower()

# Extract the username and domain
username, domain = cleaned_input.split("@")

# Convert the username to title case
username = username.title()

print(f"Username: {username}, Domain: {domain}")

Enter your email id: abcd@gmail.com


Username: Abcd, Domain: gmail.com


# 12.Reading CSV files

In [117]:
import pandas as pd

#Reading CSV Files into Pandas DataFrames
df = pd.read_csv('Titanic dataset/train.csv')
# Display the first few rows of the DataFrame
print(df.head())


   PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  


In [118]:
#Reading CSV with CSV Module

import csv

#This code reads a CSV file using the csv module and prints each row.

with open('Titanic dataset/train.csv', mode='r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp', 'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked']
['1', '0', '3', 'Braund, Mr. Owen Harris', 'male', '22', '1', '0', 'A/5 21171', '7.25', '', 'S']
['2', '1', '1', 'Cumings, Mrs. John Bradley (Florence Briggs Thayer)', 'female', '38', '1', '0', 'PC 17599', '71.2833', 'C85', 'C']
['3', '1', '3', 'Heikkinen, Miss. Laina', 'female', '26', '0', '0', 'STON/O2. 3101282', '7.925', '', 'S']
['4', '1', '1', 'Futrelle, Mrs. Jacques Heath (Lily May Peel)', 'female', '35', '1', '0', '113803', '53.1', 'C123', 'S']
['5', '0', '3', 'Allen, Mr. William Henry', 'male', '35', '0', '0', '373450', '8.05', '', 'S']
['6', '0', '3', 'Moran, Mr. James', 'male', '', '0', '0', '330877', '8.4583', '', 'Q']
['7', '0', '1', 'McCarthy, Mr. Timothy J', 'male', '54', '0', '0', '17463', '51.8625', 'E46', 'S']
['8', '0', '3', 'Palsson, Master. Gosta Leonard', 'male', '2', '3', '1', '349909', '21.075', '', 'S']
['9', '1', '3', 'Johnson, Mrs. Oscar W (Elis

In [119]:
#Reading Specific Columns
import pandas as pd

df = pd.read_csv('Titanic dataset/train.csv', usecols=['PassengerId', 'Name'])
print(df)

     PassengerId                                               Name
0              1                            Braund, Mr. Owen Harris
1              2  Cumings, Mrs. John Bradley (Florence Briggs Th...
2              3                             Heikkinen, Miss. Laina
3              4       Futrelle, Mrs. Jacques Heath (Lily May Peel)
4              5                           Allen, Mr. William Henry
..           ...                                                ...
886          887                              Montvila, Rev. Juozas
887          888                       Graham, Miss. Margaret Edith
888          889           Johnston, Miss. Catherine Helen "Carrie"
889          890                              Behr, Mr. Karl Howell
890          891                                Dooley, Mr. Patrick

[891 rows x 2 columns]


In [120]:
#Handling Missing Values
#handles missing values in a CSV file by filling them with 'Unknown'.

import pandas as pd

df = pd.read_csv('Titanic dataset/train.csv')
df = df.fillna('Unknown')
print(df)
    

     PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex      Age  \
0                              Braund, Mr. Owen Harris    male     22.0   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female     38.0   
2                               Heikkinen, Miss. Laina  female     26.0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female     35.0   
4                             Allen, Mr. William Henry    male     35.0   
..                                                 ...     ...      ...   
886               

In [122]:
#Reading CSV with Index Column
#This code reads a CSV file and sets a specific column as the index.

import pandas as pd

df = pd.read_csv('Titanic dataset/train.csv', index_col='PassengerId')
print(df)

             Survived  Pclass  \
PassengerId                     
1                   0       3   
2                   1       1   
3                   1       3   
4                   1       1   
5                   0       3   
...               ...     ...   
887                 0       2   
888                 1       1   
889                 0       3   
890                 1       1   
891                 0       3   

                                                          Name     Sex   Age  \
PassengerId                                                                    
1                                      Braund, Mr. Owen Harris    male  22.0   
2            Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0   
3                                       Heikkinen, Miss. Laina  female  26.0   
4                 Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0   
5                                     Allen, Mr. William Henry    male  35.0   
...       

# 13. Numpy
- NumPy is a powerful library for numerical computing in Python. It provides support for arrays and mathematical operations. 

In [123]:
import numpy as np

In [132]:
#1-D Arrays
arr1 = np.array([1, 2, 3, 4, 5])
print('1-D array containing the values\n',arr1)

#2-D Arrays
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print('2-D array containing the values\n',arr2)

#3-D arrays
arr3 = np.array([[1, 2, 3], [4, 5, 6], [1, 2, 3]])
print('3-D array containing the values\n',arr3)

1-D array containing the values
 [1 2 3 4 5]
2-D array containing the values
 [[1 2 3]
 [4 5 6]]
3-D array containing the values
 [[1 2 3]
 [4 5 6]
 [1 2 3]]


In [140]:
myarr = np.array([3,6,32,7])

myarr

array([ 3,  6, 32,  7])

In [142]:
# Get Dimension
print('number of dimensions :', myarr.ndim)

# Get Shape
print('Shape of array :', myarr.shape)

# Get Type
print('Type of array :', myarr.dtype)

# Get Size
myarr.itemsize
print('size of array :', myarr.itemsize)

# Get total size
print('total size of array :', myarr.nbytes)

# Get number of elements
print('number of elements :', myarr.size)

number of dimensions : 1
Shape of array : (4,)
Type of array : int32
size of array : 4
total size of array : 16
number of elements : 4


In [143]:
#Accessing/Changing specific elements, rows, columns, etc
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [148]:
# Get a specific element [r, c]
print('specific element:',a[1, 5])

# Get a specific row
print('specific row:',a[0, :])

# Get a specific column
print('specific column:',a[:, 2])

# Slicing arrays [startindex:endindex:stepsize]
print('Slicing array result1 \n',a[1, 1:4]) #From the second element, slice elements from index 1 to index 4 (not included)
print('Slicing array result2 \n',a[0:2, 2]) #From both elements, return index 2
print('Slicing array result3 \n',a[0:2, 1:4]) #From both elements, slice index 1 to index 4 (not included)

specific element: 13
specific row: [1 2 3 4 5 6 7]
specific column: [ 3 10]
Slicing array result1 
 [ 9 10 11]
Slicing array result2 
 [ 3 10]
Slicing array result3 
 [[ 2  3  4]
 [ 9 10 11]]


In [149]:
#zeros
zeros = np.zeros((2,5))
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [150]:
rng = np.arange(15)
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [151]:
#linspace
lspace = np.linspace(1,50,10) # (1st element,last element and how many number I need)
lspace

array([ 1.        ,  6.44444444, 11.88888889, 17.33333333, 22.77777778,
       28.22222222, 33.66666667, 39.11111111, 44.55555556, 50.        ])

In [152]:
ide= np.identity(45) #identity matrix
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [158]:
#Array copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()


print('original array',arr)
print('copy array:',x)

original array [1 2 3 4 5]
copy array: [1 2 3 4 5]


In [157]:
#view
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()

print('original array',arr)
print('view array:',x)

original array [1 2 3 4 5]
view array: [1 2 3 4 5]


In [159]:
#Array Operations
array = np.array([1, 2, 3])
array_squared = array ** 2
print(array_squared) 

[1 4 9]


In [160]:
#Matrix Multiplication
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[2, 0], [1, 3]])
product = np.dot(matrix1, matrix2)
print(product)

[[ 4  6]
 [10 12]]


In [161]:
#statistical Operations

data = np.array([1, 2, 3, 4, 5])
mean = np.mean(data)
std_dev = np.std(data)
print(f"Mean: {mean}, Std Dev: {std_dev}")  # This code calculates the mean and standard deviation of a NumPy array.


Mean: 3.0, Std Dev: 1.4142135623730951


In [162]:
#Array Reshaping
#This code reshapes a NumPy array from a 1D array to a 2D array.

array = np.arange(12)
reshaped_array = array.reshape(3, 4)
print(reshaped_array)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


# 14.Pandas: Pandas is a library used for data manipulation and analysis. It provides data structures like DataFrames for handling structured data. 

In [165]:
import pandas as pd

In [166]:
# Creating a Series
data = pd.Series([10, 20, 30, 40, 50], name='Numbers')
print(data)

0    10
1    20
2    30
3    40
4    50
Name: Numbers, dtype: int64


In [167]:
# Creating a DataFrame
dict1 ={'Name':['Priyang','Aadhya','Krisha','Vedant'],
        'Marks':[98,89,99,87],
        'Gender':['Female','Female','Female','Male'],
        'city':['Mumbai','Delhi','Bangalore','Chennai']
}
df1=pd.DataFrame(dict1)
df1

Name  Marks  Gender       city
0  Priyang     98  Female     Mumbai
1   Aadhya     89  Female      Delhi
2   Krisha     99  Female  Bangalore
3   Vedant     87    Male    Chennai

In [168]:
#Reading and Writing Data
df2 = pd.read_csv('Pandas/Pandas_tutorial/pokemon_data.csv')

In [169]:
df2

#                   Name   Type 1  Type 2  HP  Attack  Defense  \
0      1              Bulbasaur    Grass  Poison  45      49       49   
1      2                Ivysaur    Grass  Poison  60      62       63   
2      3               Venusaur    Grass  Poison  80      82       83   
3      3  VenusaurMega Venusaur    Grass  Poison  80     100      123   
4      4             Charmander     Fire     NaN  39      52       43   
..   ...                    ...      ...     ...  ..     ...      ...   
795  719                Diancie     Rock   Fairy  50     100      150   
796  719    DiancieMega Diancie     Rock   Fairy  50     160      110   
797  720    HoopaHoopa Confined  Psychic   Ghost  80     110       60   
798  720     HoopaHoopa Unbound  Psychic    Dark  80     160       60   
799  721              Volcanion     Fire   Water  80     110      120   

     Sp. Atk  Sp. Def  Speed  Generation  Legendary  
0         65       65     45           1      False  
1         80       80     60           1      False  
2        100      100     80           1      False  
3        122      120     80           1      False  
4         60       50     65           1      False  
..       ...      ...    ...         ...        ...  
795      100      150     50           6       True  
796      160      110    110           6       True  
797      150      130     70           6       True  
798      170      130     80           6       True  
799      130       90     70           6       True  

[800 rows x 12 columns]

In [170]:
print(df2.to_string()) #use to_string() to print the entire DataFrame.

       #                       Name    Type 1    Type 2   HP  Attack  Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
0      1                  Bulbasaur     Grass    Poison   45      49       49       65       65     45           1      False
1      2                    Ivysaur     Grass    Poison   60      62       63       80       80     60           1      False
2      3                   Venusaur     Grass    Poison   80      82       83      100      100     80           1      False
3      3      VenusaurMega Venusaur     Grass    Poison   80     100      123      122      120     80           1      False
4      4                 Charmander      Fire       NaN   39      52       43       60       50     65           1      False
5      5                 Charmeleon      Fire       NaN   58      64       58       80       65     80           1      False
6      6                  Charizard      Fire    Flying   78      84       78      109       85    100           1    

In [171]:
#remove index number
df2.to_csv('data_index_false.csv',index=False)
print(df2.head(5))

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65   
1  2                Ivysaur  Grass  Poison  60      62       63       80   
2  3               Venusaur  Grass  Poison  80      82       83      100   
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122   
4  4             Charmander   Fire     NaN  39      52       43       60   

   Sp. Def  Speed  Generation  Legendary  
0       65     45           1      False  
1       80     60           1      False  
2      100     80           1      False  
3      120     80           1      False  
4       50     65           1      False  


# Data Exploration

In [2]:
import pandas as pd
df2 = pd.read_csv('data.csv')
df2.head(5)

Duration  Pulse  Maxpulse  Calories
0        60    110       130     409.1
1        60    117       145     479.0
2        60    103       135     340.0
3        45    109       175     282.4
4        45    117       148     406.0

In [3]:
df2.tail(2)

Duration  Pulse  Maxpulse  Calories
167        75    120       150     320.4
168        75    125       150     330.4

In [4]:
df2.describe()

Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Duration  169 non-null    int64  
 1   Pulse     169 non-null    int64  
 2   Maxpulse  169 non-null    int64  
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB


# Data Selection and Filtering

In [7]:
df2['Pulse']

0      110
1      117
2      103
3      109
4      117
      ... 
164    105
165    110
166    115
167    120
168    125
Name: Pulse, Length: 169, dtype: int64

In [8]:
df2['Pulse'][0]

110

In [40]:
df2.at[0, 'Pulse'] = 123 #Use .at[] when you need to access or update a single cell efficiently.

#Use .loc[] when you want to access or update a subset of rows/columns, or when working with slices, filters, or conditions.
df2.loc[0, 'Pulse'] = 123
df.loc[0:2, ['Pulse', 'Calories']] 

Pulse  Calories
0    110     409.1
1    117     479.0
2    103     340.0

In [10]:
# Filtering rows where Age > 30
filtered_df = df2[df2['Duration'] > 30]
print(filtered_df)

     Duration  Pulse  Maxpulse  Calories
0          60    123       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[141 rows x 4 columns]


In [11]:
df2.to_csv('data_change.csv')

# Cleaning Data

In [13]:
#Return a new Data Frame with no empty cells:
df = pd.read_csv('Pandas/Pandas_basic/dirtydata.csv')

new_df = df.dropna()

print(new_df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [14]:
#Remove all rows with NULL values:
df.dropna(inplace = True)

print(df.to_string())

    Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'  

In [15]:
#Replace Empty Values #Replace NULL values with the number 130:
df.fillna(130, inplace = True)
df

Duration          Date  Pulse  Maxpulse  Calories
0         60  '2020/12/01'    110       130     409.1
1         60  '2020/12/02'    117       145     479.0
2         60  '2020/12/03'    103       135     340.0
3         45  '2020/12/04'    109       175     282.4
4         45  '2020/12/05'    117       148     406.0
5         60  '2020/12/06'    102       127     300.0
6         60  '2020/12/07'    110       136     374.0
7        450  '2020/12/08'    104       134     253.3
8         30  '2020/12/09'    109       133     195.1
9         60  '2020/12/10'     98       124     269.0
10        60  '2020/12/11'    103       147     329.3
11        60  '2020/12/12'    100       120     250.7
12        60  '2020/12/12'    100       120     250.7
13        60  '2020/12/13'    106       128     345.3
14        60  '2020/12/14'    104       132     379.3
15        60  '2020/12/15'     98       123     275.0
16        60  '2020/12/16'     98       120     215.2
17        60  '2020/12/17'    100       120     300.0
19        60  '2020/12/19'    103       123     323.0
20        45  '2020/12/20'     97       125     243.0
21        60  '2020/12/21'    108       131     364.2
23        60  '2020/12/23'    130       101     300.0
24        45  '2020/12/24'    105       132     246.0
25        60  '2020/12/25'    102       126     334.5
26        60      20201226    100       120     250.0
27        60  '2020/12/27'     92       118     241.0
29        60  '2020/12/29'    100       132     280.0
30        60  '2020/12/30'    102       129     380.3
31        60  '2020/12/31'     92       115     243.0

In [34]:
#Replace Only For Specified Columns
df.fillna({"Calories": 130}, inplace=True)

In [35]:
#Replace Using Mean, Median, or Mode
x = df["Calories"].mean()
df["Calories"] = df["Calories"].fillna(x)

In [36]:
x = df["Calories"].median()
df.fillna({"Calories": x}, inplace=True)

In [37]:
x = df["Calories"].mode()[0]
df["Calories"] = df["Calories"].fillna(x)

In [20]:
#Cleaning Data of Wrong Format

df['Date'] = pd.to_datetime(df['Date'],format='mixed')

In [21]:
df


Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7        450 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [22]:
#Remove rows with a NULL value in the "Date" column:
df.dropna(subset=['Date'], inplace = True)

In [23]:
# fix wrong values by replace them with something else.
df.loc[7, 'Duration'] = 45 #the value should be "45" instead of "450

In [24]:
df

Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
12        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

In [25]:
#Loop through all values in the "Duration" column.
#If the value is higher than 120, set it to 120:
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.loc[x, "Duration"] = 120

In [26]:
#Delete rows where "Duration" is higher than 120:
for x in df.index:
  if df.loc[x, "Duration"] > 120:
    df.drop(x, inplace = True)

In [27]:
#Removing Duplicates
print(df.duplicated())

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12     True
13    False
14    False
15    False
16    False
17    False
19    False
20    False
21    False
23    False
24    False
25    False
26    False
27    False
29    False
30    False
31    False
dtype: bool


In [28]:
df.drop_duplicates(inplace = True)

In [29]:
df

Duration       Date  Pulse  Maxpulse  Calories
0         60 2020-12-01    110       130     409.1
1         60 2020-12-02    117       145     479.0
2         60 2020-12-03    103       135     340.0
3         45 2020-12-04    109       175     282.4
4         45 2020-12-05    117       148     406.0
5         60 2020-12-06    102       127     300.0
6         60 2020-12-07    110       136     374.0
7         45 2020-12-08    104       134     253.3
8         30 2020-12-09    109       133     195.1
9         60 2020-12-10     98       124     269.0
10        60 2020-12-11    103       147     329.3
11        60 2020-12-12    100       120     250.7
13        60 2020-12-13    106       128     345.3
14        60 2020-12-14    104       132     379.3
15        60 2020-12-15     98       123     275.0
16        60 2020-12-16     98       120     215.2
17        60 2020-12-17    100       120     300.0
19        60 2020-12-19    103       123     323.0
20        45 2020-12-20     97       125     243.0
21        60 2020-12-21    108       131     364.2
23        60 2020-12-23    130       101     300.0
24        45 2020-12-24    105       132     246.0
25        60 2020-12-25    102       126     334.5
26        60 2020-12-26    100       120     250.0
27        60 2020-12-27     92       118     241.0
29        60 2020-12-29    100       132     280.0
30        60 2020-12-30    102       129     380.3
31        60 2020-12-31     92       115     243.0

# Advanced Functionality

In [30]:
# Merging DataFrames
df1 = pd.DataFrame({'ID': [1, 2, 3], 'Name': ['Alice', 'Bob', 'Charlie']})
df2 = pd.DataFrame({'ID': [1, 2, 4], 'Age': [25, 30, 40]})
merged_df = pd.merge(df1, df2, on='ID', how='inner')
print(merged_df)

   ID   Name  Age
0   1  Alice   25
1   2    Bob   30


In [5]:
# Creating a pivot table
import pandas as pd
data = {"value": range(12),
       "variable": ["A"] * 3 + ["B"] * 3 + ["C"] * 3 + ["D"] * 3,
    "date": pd.to_datetime(["2020-01-03", "2020-01-04", "2020-01-05"] * 4) }
    
df = pd.DataFrame(data)
df

value variable       date
0       0        A 2020-01-03
1       1        A 2020-01-04
2       2        A 2020-01-05
3       3        B 2020-01-03
4       4        B 2020-01-04
5       5        B 2020-01-05
6       6        C 2020-01-03
7       7        C 2020-01-04
8       8        C 2020-01-05
9       9        D 2020-01-03
10     10        D 2020-01-04
11     11        D 2020-01-05

In [6]:
pivoted = df.pivot(index="date", columns="variable", values="value")

pivoted

variable    A  B  C   D
date                   
2020-01-03  0  3  6   9
2020-01-04  1  4  7  10
2020-01-05  2  5  8  11

In [32]:
# Creating a crosstab
crosstab = pd.crosstab(df2['ID'], df2['Age'])
print(crosstab)

Age  25  30  40
ID             
1     1   0   0
2     0   1   0
4     0   0   1


# Data Correlations
- # Perfect Correlation: "Duration" and "Duration" got a 1.000000 correlation
- # Good Correlation: "Duration" and "Calories" got a 0.922721 correlation
- # Bad Correlation: "Duration" and "Maxpulse" got a 0.009403 correlation

In [33]:
df.corr()

Duration      Date     Pulse  Maxpulse  Calories
Duration  1.000000  0.217700 -0.183526 -0.391753  0.350969
Date      0.217700  1.000000 -0.380088 -0.549973 -0.368101
Pulse    -0.183526 -0.380088  1.000000  0.200177  0.503243
Maxpulse -0.391753 -0.549973  0.200177  1.000000  0.338515
Calories  0.350969 -0.368101  0.503243  0.338515  1.000000

In [41]:
#Concatenating DataFrames
# Concatenate two DataFrames row-wise
df_concatenated = pd.concat([df1, df2], axis=0)

# Concatenate two DataFrames column-wise
df_concatenated_cols = pd.concat([df1, df2], axis=1)

In [44]:
data = {'EmployeeID': [101, 102, 103],
        'Name': ['John', 'Jane', 'Mike'],
        'Salary': [60000, 65000, 70000]}
df = pd.DataFrame(data)
df

EmployeeID  Name  Salary
0         101  John   60000
1         102  Jane   65000
2         103  Mike   70000

In [45]:
# Create a new column 'NetSalary' by applying a custom function
def calculate_net_salary(salary):
    return salary * 0.8  # Deduct 20% for tax

df['NetSalary'] = df['Salary'].apply(calculate_net_salary)

In [46]:
df

EmployeeID  Name  Salary  NetSalary
0         101  John   60000    48000.0
1         102  Jane   65000    52000.0
2         103  Mike   70000    56000.0

# File Handling
Python provides built-in functions for reading and writing files. You can open a file using the open() function, and then read or write data to it.

In [1]:
with open("output.txt", "w") as file:
    file.write("This is a sample output.")


In [2]:
with open("output.txt", "r") as file:
    content = file.read()
    print(content)

This is a sample output.


# Exception Handling
Errors can occur during the execution of a program. To handle these errors gracefully, Python provides exception handling using the try-except block.

In [3]:
try:
    result = 10 / 0
except ZeroDivisionError:
    print("Error: Division by zero is not allowed.")


Error: Division by zero is not allowed.


# Modules and Packages
Python's functionality can be extended by using modules and packages. A module is a file containing Python code, while a package is a collection of modules.

You can import built-in or third-party modules to use additional functionality in your code.

In [4]:
import math
print(math.sqrt(16))

4.0


# Object-Oriented Programming (OOP)
Python supports object-oriented programming (OOP), which allows you to define classes and create objects. Classes are blueprints for objects, and objects are instances of classes.

In [5]:
class Car:
    def __init__(self, brand, model):
        self.brand = brand
        self.model = model

    def drive(self):
        return f"{self.brand} {self.model} is driving."

car1 = Car("Toyota", "Camry")
print(car1.drive())

Toyota Camry is driving.
